module.exports = {
  1: {
    box_id: 1,
    title: 'GACHA BOX',
    name: 'Gold Chest',
    type: "gold",
    price: 5999,
    total: 0,
    opened: 0,
    stock: 0,
  },
  2: {
    box_id: 2,
    title: 'GACHA BOX',
    name: 'Platinum Chest',
    type: "platinum",
    price: 11999,
    total: 0,
    opened: 0,
    stock: 0,
  },
  3: {
    box_id: 3,
    title: 'GACHA BOX',
    name: 'Herald Chest',
    price: 21999,
    type: "herald",
    total: 0,
    opened: 0,
    stock: 0,
  },
  4: {
    box_id: 4,
    title: 'GACHA BOX',
    name: 'Ruby Chest',
    type: "ruby",
    price: 38999,
    total: 0,
    opened: 0,
    stock: 0,
  },
  5: {
    box_id: 5,
    title: 'GACHA BOX',
    name: 'Diamond Chest',
    type: "diamond",
    price: 68999,
    total: 0,
    opened: 0,
    stock: 0,
  },
  6: {
    box_id: 1,
    title: 'GACHA BOX',
    name: 'Gold Chest',
    type: "gold",
    price: 5999,
    total: 0,
    opened: 0,
    stock: 0,
  },
  7: {
    box_id: 2,
    title: 'GACHA BOX',
    name: 'Platinum Chest',
    type: "platinum",
    price: 11999,
    total: 0,
    opened: 0,
    stock: 0,
  },
  8: {
    box_id: 3,
    title: 'GACHA BOX',
    name: 'Herald Chest',
    price: 21999,
    type: "herald",
    total: 0,
    opened: 0,
    stock: 0,
  },
  9: {
    box_id: 4,
    title: 'GACHA BOX',
    name: 'Ruby Chest',
    type: "ruby",
    price: 38999,
    total: 0,
    opened: 0,
    stock: 0,
  },
  10: {
    box_id: 5,
    title: 'GACHA BOX',
    name: 'Diamond Chest',
    type: "diamond",
    price: 68999,
    total: 0,
    opened: 0,
    stock: 0,
  }
};
